# .travis.yml
before_install:
- dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8
install:
- npm ci
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run test
- npm run flow
